### ISSUE TITLE
Question about the evaluation part

### ISSUE THREAD

**Issue by Fleurrr** [yurimjeon1892/EFGH#2]
Thanks for your nice work, I have two questions about the evaluation:
1). Are Test1-E to Test1-H on the Kitti odometry corresponds to the sequence 07-10?
2). The Rotation and translation augmentation scale when doing evaluation?
Looking forward to your reply!

**Comment by yurimjeon1892** [comment]
Thank you for your question.
1) Test-E to Test-H were all evaluated using seq 9 and 10 of the KITTI Odometry dataset. Different test sets use different configurations. Please refer to Table 1 of the paper.
2) Rotation and translation scales are also described in Table 1 of the paper.

Good luck!

**Comment by Fleurrr** [comment]
> Thank you for your question.
> 
> 1. Test-E to Test-H were all evaluated using seq 9 and 10 of the KITTI Odometry dataset. Different test sets use different configurations. Please refer to Table 1 of the paper.
> 2. Rotation and translation scales are also described in Table 1 of the paper.
> 
> Good luck!

Ah sorry, I missed Table I.
The translation scales when training is ±10m right?

**Comment by yurimjeon1892** [comment]
In the config file used for training (configs/train_rellis.yaml), the **translation_max** parameter corresponds to the distance between the image frame and the point cloud frame, set at 10 meters. In agumentation process, an extra 2-meter translation noise is added (corresponds to  **dclb/l_trs_range** parameter).

**Comment by Fleurrr** [comment]
> In the config file used for training (configs/train_rellis.yaml), the **translation_max** parameter corresponds to the distance between the image frame and the point cloud frame, set at 10 meters. In agumentation process, an extra 2-meter translation noise is added (corresponds to **dclb/l_trs_range** parameter).

I see.
Grateful to your quick reply!
