### ISSUE TITLE
How to process KITTI dataset?

### ISSUE THREAD

**Issue by kiinchen** [yurimjeon1892/EFGH#3]
Thanks to your excellent work on EFGHNet. Now i'm designing a comprehensive pointcloud processing method on KITTI. Can you tell the detail about how you process KITTI dataset until it can be used in EFGHNet?

**Comment by yurimjeon1892** [comment]
In the KITTI dataset, for images, there are processes of size cropping, resizing, and image rotation, while for point clouds, there are processes of point random sampling, rotation, and translation.

**Comment by yurimjeon1892** [comment]
Close this issue.
