### ISSUE TITLE
Results not proper

### ISSUE THREAD

**Issue by negiabhinit** [yurimjeon1892/EFGH#6]
I tried doing this Still couldn't make much sense of the results!
Can you help?
![00000_001720_001727_pred_depth_EFH](https://github.com/yurimjeon1892/EFGH/assets/38641617/e08a2484-afae-4e6e-a8cd-464a2d2bd517)

I have already tried this https://github.com/yurimjeon1892/EFGH/issues/4#issuecomment-1647207564

**Comment by yurimjeon1892** [comment]
Hello. It would be helpful for troubleshooting if you could provide information about the configuration file used in the inference. Did you use the checkpoints we uploaded?

Also, is this result observed only in one sample, or does registration fail in all samples in the sequence?

Thank you.

**Comment by negiabhinit** [comment]
This the config file used  
# general args
test: test
ckpt_path: /home/abhnegi/EFGH/weights/rellis2_nipa_efgh/model_best.pth.tar

arch: EFGH
last_relu: False

use_leaky: True
bcn_use_bias: True
bcn_use_norm: True

DEVICE: cuda

# Dataset
dataset: RELLIS_3D
data_root: /pfs/rdi/cea/rdicea_vru/01_Datasets/RELLIS-3D/
num_points: 65536
lidar_line: 64
lidar_fov_rad: [0.125, -0.125]
raw_cam_img_size: [900, 1600]

val_samples: -1

# for model
dim: 3
batch_size: 1
scale_map: [[1., 1],
            [0.75, 1],
            [0.5, 1],
            [0.25, 1],
            [0.125, 1],
            ]

# miscalleneous
workers: 4

delta_ij_max: 40
translation_max: 10.
accumulation_frame_num: 0
accumulation_frame_skip: 1

rand_init: ./params/rellis3d_rand_init_30_30.csv
save_image: True

**Comment by negiabhinit** [comment]
Registration failed for all the frames.

**Comment by yurimjeon1892** [comment]
Would you like to try using a different model? The current rellis2_nipa_efgh model is trained with the **accumulation_frame_num: 5** setting. Try using the **rellis_nipa_efgh** model instead.

**Comment by negiabhinit** [comment]
Here are the results from rellis_nipa_efgh
![00000_001706_001788_pred_depth_EH](https://github.com/yurimjeon1892/EFGH/assets/38641617/0e1a9c20-3180-4b13-923d-572734b13452)

**Comment by negiabhinit** [comment]
The point cloud doesn't seem to be aligned.

**Comment by yurimjeon1892** [comment]
I apologize for the delayed response. If the initial noise is very large, it may result in unstable prediction outcomes.

**Comment by yurimjeon1892** [comment]
I am closing this issue here. Please reopen it if any problems occur.
