### ISSUE TITLE
Dataset issues!

### ISSUE THREAD

**Issue by cnu-Dawn** [yurimjeon1892/EFGH#7]
Why is there no transformers.ymal in the downloaded dataset!

**Comment by yurimjeon1892** [comment]
You can download the _transforms.yaml_ file via link in RELLIS-3D github page (https://github.com/unmannedlab/RELLIS-3D).

**Basler Camera to Ouster LiDAR** ([Download 3KB](https://drive.google.com/file/d/19EOqWS9fDUFp4nsBrMCa69xs9LgIlS2e/view?usp=sharing))

**Comment by cnu-Dawn** [comment]
Sorry, he has encountered a new error FileNotFoundError:/data/RELLIS-3D/Rellis-3D/00000/camera_info.exe not found
I found from the link: https://pan.baidu.com/s/1akqSm7mpIMyUJhn_qwg3-w?pwd=4gk3 The structure of the downloaded dataset is very chaotic. Do you have a more organized dataset
