### ISSUE TITLE
The correct dataset

### ISSUE THREAD

**Issue by cnu-Dawn** [yurimjeon1892/EFGH#8]
data
└── RELLIS-3D
    ├── RELLIS-3D
    |   ├── 00000
    |   |   ├── os1_cloud_node_kitti_bin
    |   |   ├── pylon_camera_node
    |   |   ├── calib.txt
    |   |   ├── poses.txt
    |   |   └── camera_info.txt    
    |   ├── 00001
    |   └── ..
    ├── RELLIS_3D
    |   ├── 00000
    |   |   └── transforms.yaml
    |   ├── 00001
    |   └── ..
    ├── pt_test.lst
    ├── pt_train.lst
    └── pt_val.lst
Do you have a dataset in this format? The dataset downloaded from Baidu Cloud is missing many files

**Comment by yurimjeon1892** [comment]
Yes, that's correct. Is it not possible to download the files in the structure mentioned above from the download link provided by the author of rellis-3d? Which specific file is missing?

**Comment by cnu-Dawn** [comment]
no camera_info.txt ! how to find it?

**Comment by yurimjeon1892** [comment]
You can download the _camera_info.txt_ file from the **Calibration Download: Camera Instrinsic** file link on the rellis-3d GitHub.

**Comment by yurimjeon1892** [comment]
Close this issue.
